### ISSUE TITLE
First level should maintain all first level options.

### ISSUE THREAD

**Issue by Desertsnowman** [FacetWP/facetwp-hierarchy-select#1]
Just noticed that the first level looses all possible options when selected.
Child levels chould only have options that relate to the above option.
![not-maintaining](https://cloud.githubusercontent.com/assets/307466/24341886/52909132-12bd-11e7-85c0-fd8db7dc974b.gif)

**Comment by mgibbs189** [comment]
@Desertsnowman this could apply to all levels, not just top-level
