### ISSUE TITLE
User selections

### ISSUE THREAD

**Issue by marcelaerts** [FacetWP/facetwp-hierarchy-select#4]
When using a hierachy select with 2 or more levels my facetwp-selections break down when clicking the close button of the first level.

Error:
Uncaught TypeError: Cannot read property 'label' of undefined.
(plugins/facetwp/assets/js/front.js?ver=2.8.7)

When clicking the second time it works.

**Comment by mgibbs189** [comment]
Thanks @marcelaerts we'll investigate!

**Comment by mgibbs189** [comment]
Not able to reproduce in FWP 3.0.9.1 + v0.2.1 of the Hierarchy Select add-on. Please re-open w/ more details if you're still experiencing the issue 👍
