### ISSUE TITLE
Error saving new facet

### ISSUE THREAD

**Issue by thomasjohnkane** [FacetWP/facetwp-hierarchy-select#5]
Hello,

When trying to save a new facet, the facet never saves. It simply keeps saying "saving...". No errors appear to pop up.

Is this something you have seen before? Can you point me in the right direction?

**Comment by mgibbs189** [comment]
@thomasjohnkane Please open a ticket (Settings > FacetWP > Support) and we'll take a look.

**Comment by thomasjohnkane** [comment]
Thanks, I submitted this as ticket.
