### ISSUE TITLE
Hierarchal checkboxes are showing up empty

### ISSUE THREAD

**Issue by mvdhoek1** [FacetWP/facetwp-hierarchy-select#9]
Hi facetWP,

I could not find the correct repository for this issue therefore I'm using this one. My issue occurred when using checkboxes.

When using a hierarchal taxonomy as a filter it does not show the children terms.
I've tried using WP version 5.2 and 5.3 and I've also downgraded facetWP but nothing works. 
Is this a known error?

Wordpress: v5.3.2
FacetWP: v3.5.0.1 

<img width="1266" alt="Schermafbeelding 2020-03-30 om 09 41 11" src="https://user-images.githubusercontent.com/11852816/77887709-59177c80-726b-11ea-946c-ba9281120922.png">
<img width="1440" alt="Schermafbeelding 2020-03-30 om 09 40 27" src="https://user-images.githubusercontent.com/11852816/77887720-5c126d00-726b-11ea-96c7-54b5c61d693b.png">

**Comment by mvdhoek1** [comment]
Hi facetWP,

Could you guys give me an update? My company is a paid customer and we need to solve this.

Thanks in advance!

**Comment by mgibbs189** [comment]
@mvdhoek1 this is **not** a support forum. Please open a support ticket via `Settings > FacetWP > Support` in your site's dashboard
